<?php

namespace SwaggerCustom\Test\TestCase;

use Cake\TestSuite\IntegrationTestTrait;
use Cake\TestSuite\TestCase;

class ControllerTest extends TestCase
{
    use IntegrationTestTrait;

    /**
     * @var string[]
     */
    public $fixtures = [
        'plugin.SwaggerCustom.Departments',
    ];

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        static::setAppNamespace('SwaggerCustomTest\App');
    }

    public function testSwaggerIndex()
    {
        $this->get('/');
        $this->assertResponseOk();
    }

    public function testRedocIndex()
    {
        $this->get('/?doctype=redoc');
        $this->assertResponseOk();
    }
}